# [test/runtests.jl]

#   Note that the comparison files for these tests were generated by 
# running the MATLAB code on the same variables and storing the results

using EarthAlbedo 
using Test 
using JLD2

# Test scripts 
include("rad2idx_tests.jl")
include("idx2rad_tests.jl")
include("gridangle_tests.jl")
include("earthfov_tests.jl")
include("cellarea_tests.jl")
include("earth_albedo_tests.jl")